### ISSUE TITLE
Combining Two Categories

### ISSUE THREAD

**Issue by WeirdFoodStudio** [hkeward/weirdfoodstudio#13]
I'd like to combine the entries for Physical (analogue) and digital illustrations on the menu, under the new header "Illustrations".  Ideally, when you click on the hamburger, there will be an entry on the menu called "Illustrations" and when you click on that, instead of immediately redirecting, two smaller entries appear underneath (physical and digital).

If this isn't possible, or would be too difficult/take too long, then I'm very into collapsing both categories and just having one big area called "Illustrations".

**Comment by hkeward** [comment]
@WeirdFoodStudio here is my first pass. Currently rather than having a clickable `Illustrations` that expands out into another menu I have `Digital` and `Physical` options split out underneath the Illustrations header. WDYT? Would you prefer to have these initially hidden and have `Illustrations` be clickable to expand that further menu as you described, or does this work?

![navbar](https://user-images.githubusercontent.com/13265645/210194487-be827937-290c-44b8-8785-a8be0fda3e85.png)

Currently "Illustrations" is not clickable; I think if you want to go with this we should style it differently (italics? font colour?) to imply to the user that this is not a clickable category like the other links at that indentation level.

**Comment by hkeward** [comment]
Possible way to distinguish clickable vs. unclickable sections:

1. Underline links
![navbar_underline](https://user-images.githubusercontent.com/13265645/210194967-9657e733-1a7c-4eec-b1bb-bacbcbd08097.png)

2. Underline non-links
![navbar_underline_illustrations](https://user-images.githubusercontent.com/13265645/210194983-824fe025-2205-44a5-b6ab-6dbd5dde6ba4.png)

We could also have Illustrations be clickable, leading to a page that itself has only links to Digital and Physical.
